version: 2
jobs:
  build:
    docker:
      - image: debian:stretch

    steps:

      - run:
          name: Install Dependencies
          command: apt update && apt install -y build-essential cmake ninja-build git

      - checkout

      - run:
          name: "Pull Submodules"
          command: |
            git submodule init
            git submodule update --remote

      - run:
          name: CMake
          command: mkdir -p /tmp/doxygen2docset/build && cd /tmp/doxygen2docset/build && cmake /root/project -G Ninja -DCMAKE_BUILD_TYPE=Release

      - run:
          name: Build with Ninja
          command: ninja -C /tmp/doxygen2docset/build

      - run:
          name: Run Unit-Tests
          command: /tmp/doxygen2docset/build/tests/doxygen2docset_unittests

      - run:
          name: Package Release Artifacts
          command: ninja -C /tmp/doxygen2docset/build package

      - store_artifacts:
          path: /tmp/doxygen2docset/build/source/doxygen2docset-0.1.1-Linux.deb
          destination: doxygen2docset
