Flutter Engine: flutter::Shell Class Reference
flutter::Shell Class Reference final
#include <shell.h>
Public Types
template<class T >
using CreateCallback = std::function< std::unique_ptr< T >(Shell &)>
Public Types inherited from flutter::ServiceProtocol::Handler
using ServiceProtocolMap = std::map< std::string_view, std::string_view >
Public Member Functions
~Shell ()
Destroys the shell. This is a synchronous operation and synchronous barrier blocks are introduced on the various threads to ensure shutdown of all shell sub-components before this method returns.
void RunEngine (RunConfiguration run_configuration)
Starts an isolate for the given RunConfiguration.
void RunEngine (RunConfiguration run_configuration, std::function< void(Engine::RunStatus)> result_callback)
Starts an isolate for the given RunConfiguration. The result_callback will be called with the status of the operation.
const Settings & GetSettings () const
const TaskRunners & GetTaskRunners () const
If callers wish to interact directly with any shell subcomponents, they must (on the platform thread) obtain a task runner that the component is designed to run on and a weak pointer to that component. They may then post a task to that task runner, do the validity check on that task runner before performing any operation on that component. This accessor allows callers to access the task runners for this shell.
fml::WeakPtr< Rasterizer > GetRasterizer ()
Rasterizers may only be accessed on the GPU task runner.
fml::WeakPtr< PlatformView > GetPlatformView ()
Platform views may only be accessed on the platform task runner.
void NotifyLowMemoryWarning () const
Used by embedders to notify that there is a low memory warning. The shell will attempt to purge caches. Current, only the rasterizer cache is purged.
bool IsSetup () const
Used by embedders to check if all shell subcomponents are initialized. It is the embedder's responsibility to make this call before accessing any other shell method. A shell that is not setup must be discarded and another one created with updated settings.
Rasterizer::Screenshot Screenshot (Rasterizer::ScreenshotType type, bool base64_encode)
Captures a screenshot and optionally Base64 encodes the data of the last layer tree rendered by the rasterizer in this shell.
fml::Status WaitForFirstFrame (fml::TimeDelta timeout)
Pauses the calling thread until the first frame is presented.
std::optional< DartErrorCode > GetUIIsolateLastError () const
Used by embedders to get the last error from the Dart UI Isolate, if one exists.
bool EngineHasLivePorts () const
Used by embedders to check if the Engine is running and has any live ports remaining. For example, the Flutter tester uses this method to check whether it should continue to wait for a running test or not.
Public Member Functions inherited from flutter::PlatformView::Delegate
virtual void OnPlatformViewRegisterTexture (std::shared_ptr< Texture > texture)=0
Notifies the delegate that the embedder has specified a texture that it want the rasterizer to composite within the Flutter layer tree. All textures must have a unique identifier. When the rasterizer encounters an external texture within its hierarchy, it gives the embedder a chance to update that texture on the GPU thread before it composites the same on-screen.
Static Public Member Functions
static std::unique_ptr< Shell > Create (TaskRunners task_runners, Settings settings, CreateCallback< PlatformView > on_create_platform_view, CreateCallback< Rasterizer > on_create_rasterizer)
Creates a shell instance using the provided settings. The callbacks to create the various shell subcomponents will be called on the appropriate threads before this method returns. If this is the first instance of a shell in the process, this call also bootstraps the Dart VM.
static std::unique_ptr< Shell > Create (TaskRunners task_runners, Settings settings, fml::RefPtr< const DartSnapshot > isolate_snapshot, fml::RefPtr< const DartSnapshot > shared_snapshot, CreateCallback< PlatformView > on_create_platform_view, CreateCallback< Rasterizer > on_create_rasterizer, DartVMRef vm)
Creates a shell instance using the provided settings. The callbacks to create the various shell subcomponents will be called on the appropriate threads before this method returns. Unlike the simpler variant of this factory method, this method allows for the specification of an isolate snapshot that cannot be adequately described in the settings. This call also requires the specification of a running VM instance.
Friends
class testing::ShellTest
Detailed Description
Perhaps the single most important class in the Flutter engine repository. When embedders create a Flutter application, they are referring to the creation of an instance of a shell. Creation and destruction of the shell is synchronous and the embedder only holds a unique pointer to the shell. The shell does not create the threads its primary components run on. Instead, it is the embedder's responsibility to create threads and give the shell task runners for those threads. Due to deterministic destruction of the shell, the embedder can terminate all threads immediately after collecting the shell. The shell must be created and destroyed on the same thread, but, different shells (i.e. a separate instances of a Flutter application) may be run on different threads simultaneously. The task runners themselves do not have to be unique. If all task runner references given to the shell during shell creation point to the same task runner, the Flutter application is effectively single threaded.
The shell is the central nervous system of the Flutter application. None of the shell components are thread safe and must be created, accessed and destroyed on the same thread. To interact with one another, the various components delegate to the shell for communication. Instead of using back pointers to the shell, a delegation pattern is used by all components that want to communicate with one another. Because of this, the shell implements the delegate interface for all these components.
All shell methods accessed by the embedder may only be called on the platform task runner. In case the embedder wants to directly access a shell subcomponent, it is the embedder's responsibility to acquire a weak pointer to that component and post a task to the task runner used by the component to access its methods.
There is no explicit API to bootstrap and shutdown the Dart VM. The first instance of the shell in the process bootstraps the Dart VM and the destruction of the last shell instance destroys the same. Since different shells may be created and destroyed on different threads. VM bootstrap may happen on one thread but its collection on another. This behavior is thread safe.
Definition at line 87 of file shell.h.
Member Typedef Documentation
CreateCallback
template<class T > using flutter::Shell::CreateCallback = std::function<std::unique_ptr<T>(Shell&)>
Definition at line 94 of file shell.h.
Constructor & Destructor Documentation
~Shell()
flutter::Shell::~Shell ()
Destroys the shell. This is a synchronous operation and synchronous barrier blocks are introduced on the various threads to ensure shutdown of all shell sub-components before this method returns.
Definition at line 311 of file shell.cc.
               {
   PersistentCache::GetCacheForProcess()->RemoveWorkerTaskRunner(
       task_runners_.GetIOTaskRunner());
   vm_->GetServiceProtocol()->RemoveHandler(this);
   fml::AutoResetWaitableEvent ui_latch, gpu_latch, platform_latch, io_latch;
   fml::TaskRunner::RunNowOrPostTask(
       task_runners_.GetUITaskRunner(),
       fml::MakeCopyable([engine = std::move(engine_), &ui_latch]() mutable {
         engine.reset();
         ui_latch.Signal();
       }));
   ui_latch.Wait();
   fml::TaskRunner::RunNowOrPostTask(
       task_runners_.GetGPUTaskRunner(),
       fml::MakeCopyable(
           [rasterizer = std::move(rasterizer_), &gpu_latch]() mutable {
             rasterizer.reset();
             gpu_latch.Signal();
           }));
   gpu_latch.Wait();
   fml::TaskRunner::RunNowOrPostTask(
       task_runners_.GetIOTaskRunner(),
       fml::MakeCopyable([io_manager = std::move(io_manager_),
                          platform_view = platform_view_.get(),
                          &io_latch]() mutable {
         io_manager.reset();
         if (platform_view) {
           platform_view->ReleaseResourceContext();
         }
         io_latch.Signal();
       }));
   io_latch.Wait();
   // The platform view must go last because it may be holding onto platform side
   // counterparts to resources owned by subsystems running on other threads. For
   // example, the NSOpenGLContext on the Mac.
   fml::TaskRunner::RunNowOrPostTask(
       task_runners_.GetPlatformTaskRunner(),
       fml::MakeCopyable([platform_view = std::move(platform_view_),
                          &platform_latch]() mutable {
         platform_view.reset();
         platform_latch.Signal();
       }));
   platform_latch.Wait();
 }
References engine, flutter::PersistentCache::GetCacheForProcess(), flutter::TaskRunners::GetGPUTaskRunner(), flutter::TaskRunners::GetIOTaskRunner(), flutter::TaskRunners::GetPlatformTaskRunner(), flutter::DartVM::GetServiceProtocol(), flutter::TaskRunners::GetUITaskRunner(), fml::MakeCopyable(), flutter::PersistentCache::RemoveWorkerTaskRunner(), fml::TaskRunner::RunNowOrPostTask(), fml::AutoResetWaitableEvent::Signal(), and fml::AutoResetWaitableEvent::Wait().
Member Function Documentation
Create() [1/2]
std::unique_ptr< Shell > flutter::Shell::Create (TaskRunners task_runners, Settings settings, Shell::CreateCallback< PlatformView > on_create_platform_view, Shell::CreateCallback< Rasterizer > on_create_rasterizer) static
Creates a shell instance using the provided settings. The callbacks to create the various shell subcomponents will be called on the appropriate threads before this method returns. If this is the first instance of a shell in the process, this call also bootstraps the Dart VM.
Parameters
[in] task_runners The task runners
[in] settings The settings
[in] on_create_platform_view The callback that must return a platform view. This will be called on the platform task runner before this method returns.
[in] on_create_rasterizer That callback that must provide a valid rasterizer. This will be called on the render task runner before this method returns.
Returns
A full initialized shell if the settings and callbacks are valid. The root isolate has been created but not yet launched. It may be launched by obtaining the engine weak pointer and posting a task onto the UI task runner with a valid run configuration to run the isolate. The embedder must always check the validity of the shell (using the IsSetup call) immediately after getting a pointer to it.
Definition at line 202 of file shell.cc.
{
   PerformInitializationTasks(settings);
   TRACE_EVENT0("flutter", "Shell::Create");
   auto vm = DartVMRef::Create(settings);
   FML_CHECK(vm) << "Must be able to initialize the VM.";
   auto vm_data = vm->GetVMData();
   return Shell::Create(std::move(task_runners),             //
                        std::move(settings),                 //
                        vm_data->GetIsolateSnapshot(),       // isolate snapshot
                        DartSnapshot::Empty(),               // shared snapshot
                        std::move(on_create_platform_view),  //
                        std::move(on_create_rasterizer),     //
                        std::move(vm)                        //
   );
 }
References flutter::DartVMRef::Create(), flutter::DartSnapshot::Empty(), FML_CHECK, flutter::PerformInitializationTasks(), and TRACE_EVENT0.
Referenced by flutter::AndroidShellHolder::AndroidShellHolder(), flutter::testing::ShellTest::CreateShell(), flutter_runner::Engine::Engine(), flutter::RunTester(), flutter::StartupAndShutdownShell(), and flutter::testing::TEST_F().
Create() [2/2]
std::unique_ptr< Shell > flutter::Shell::Create (TaskRunners task_runners, Settings settings, fml::RefPtr< const DartSnapshot > isolate_snapshot, fml::RefPtr< const DartSnapshot > shared_snapshot, Shell::CreateCallback< PlatformView > on_create_platform_view, Shell::CreateCallback< Rasterizer > on_create_rasterizer, DartVMRef vm) static
Creates a shell instance using the provided settings. The callbacks to create the various shell subcomponents will be called on the appropriate threads before this method returns. Unlike the simpler variant of this factory method, this method allows for the specification of an isolate snapshot that cannot be adequately described in the settings. This call also requires the specification of a running VM instance.
Parameters
[in] task_runners The task runners
[in] settings The settings
[in] isolate_snapshot A custom isolate snapshot. Takes precedence over any snapshots specified in the settings.
[in] shared_snapshot A custom shared snapshot. Takes precedence over any snapshots specified in the settings.
[in] on_create_platform_view The callback that must return a platform view. This will be called on the platform task runner before this method returns.
[in] on_create_rasterizer That callback that must provide a valid rasterizer. This will be called on the render task runner before this method returns.
[in] vm A running VM instance.
Returns
A full initialized shell if the settings and callbacks are valid. The root isolate has been created but not yet launched. It may be launched by obtaining the engine weak pointer and posting a task onto the UI task runner with a valid run configuration to run the isolate. The embedder must always check the validity of the shell (using the IsSetup call) immediately after getting a pointer to it.
Definition at line 226 of file shell.cc.
                   {
   PerformInitializationTasks(settings);
   TRACE_EVENT0("flutter", "Shell::CreateWithSnapshots");
   if (!task_runners.IsValid() || !on_create_platform_view ||
       !on_create_rasterizer) {
     return nullptr;
   }
   fml::AutoResetWaitableEvent latch;
   std::unique_ptr<Shell> shell;
   fml::TaskRunner::RunNowOrPostTask(
       task_runners.GetPlatformTaskRunner(),
       fml::MakeCopyable([&latch,                                          //
                          vm = std::move(vm),                              //
                          &shell,                                          //
                          task_runners = std::move(task_runners),          //
                          settings,                                        //
                          isolate_snapshot = std::move(isolate_snapshot),  //
                          shared_snapshot = std::move(shared_snapshot),    //
                          on_create_platform_view,                         //
                          on_create_rasterizer                             //
   ]() mutable {
         shell = CreateShellOnPlatformThread(std::move(vm),
                                             std::move(task_runners),      //
                                             settings,                     //
                                             std::move(isolate_snapshot),  //
                                             std::move(shared_snapshot),   //
                                             on_create_platform_view,      //
                                             on_create_rasterizer          //
         );
         latch.Signal();
       }));
   latch.Wait();
   return shell;
 }
References flutter::TaskRunners::GetPlatformTaskRunner(), flutter::TaskRunners::IsValid(), fml::MakeCopyable(), flutter::PerformInitializationTasks(), fml::TaskRunner::RunNowOrPostTask(), fml::AutoResetWaitableEvent::Signal(), TRACE_EVENT0, and fml::AutoResetWaitableEvent::Wait().
EngineHasLivePorts()
bool flutter::Shell::EngineHasLivePorts () const
Used by embedders to check if the Engine is running and has any live ports remaining. For example, the Flutter tester uses this method to check whether it should continue to wait for a running test or not.
Returns
Returns if the shell has an engine and the engine has any live Dart ports.
Definition at line 435 of file shell.cc.
{
   FML_DCHECK(is_setup_);
   FML_DCHECK(task_runners_.GetPlatformTaskRunner()->RunsTasksOnCurrentThread());
   // We're using the unique_ptr here because we're sure we're on the Platform
   // Thread and callers expect this to be synchronous.
   if (!engine_) {
     return false;
   }
   return engine_->UIIsolateHasLivePorts();
 }
References FML_DCHECK, flutter::TaskRunners::GetPlatformTaskRunner(), and fml::TaskRunner::RunsTasksOnCurrentThread().
Referenced by flutter::ScriptCompletionTaskObserver::DidProcessTask().
GetPlatformView()
fml::WeakPtr< PlatformView > flutter::Shell::GetPlatformView ()
Platform views may only be accessed on the platform task runner.
Returns
A weak pointer to the platform view.
Definition at line 512 of file shell.cc.
{
   FML_DCHECK(is_setup_);
   return weak_platform_view_;
 }
References FML_DCHECK.
Referenced by flutter::testing::ShellTest::PlatformViewNotifyCreated(), and flutter::testing::ValidateShell().
GetRasterizer()
fml::WeakPtr< Rasterizer > flutter::Shell::GetRasterizer ()
Rasterizers may only be accessed on the GPU task runner.
Returns
A weak pointer to the rasterizer.
Definition at line 498 of file shell.cc.
{
   FML_DCHECK(is_setup_);
   return weak_rasterizer_;
 }
References FML_DCHECK.
Referenced by flutter::testing::GetRasterizerResourceCacheBytesSync(), and Screenshot().
GetSettings()
const Settings & flutter::Shell::GetSettings () const
Returns
The settings used to launch this shell.
Definition at line 490 of file shell.cc.
{
   return settings_;
 }
GetTaskRunners()
const TaskRunners & flutter::Shell::GetTaskRunners () const
If callers wish to interact directly with any shell subcomponents, they must (on the platform thread) obtain a task runner that the component is designed to run on and a weak pointer to that component. They may then post a task to that task runner, do the validity check on that task runner before performing any operation on that component. This accessor allows callers to access the task runners for this shell.
Returns
The task runners current in use by the shell.
Definition at line 494 of file shell.cc.
{
   return task_runners_;
 }
Referenced by flutter::testing::ShellTest::CreateShell(), flutter::testing::GetRasterizerResourceCacheBytesSync(), InferOpenGLPlatformViewCreationCallback(), InferSoftwarePlatformViewCreationCallback(), flutter::testing::ShellTest::PlatformViewNotifyCreated(), flutter::testing::ShellTest::PumpOneFrame(), flutter::testing::ShellTest::RunEngine(), flutter::testing::ShellTest::SendEnginePlatformMessage(), flutter::StartupAndShutdownShell(), flutter::testing::TEST_F(), and flutter::testing::ValidateShell().
GetUIIsolateLastError()
std::optional< DartErrorCode > flutter::Shell::GetUIIsolateLastError () const
Used by embedders to get the last error from the Dart UI Isolate, if one exists.
Returns
Returns the last error code from the UI Isolate.
Definition at line 413 of file shell.cc.
{
   FML_DCHECK(is_setup_);
   FML_DCHECK(task_runners_.GetPlatformTaskRunner()->RunsTasksOnCurrentThread());
   // We're using the unique_ptr here because we're sure we're on the Platform
   // Thread and callers expect this to be synchronous.
   if (!engine_) {
     return std::nullopt;
   }
   switch (engine_->GetUIIsolateLastError()) {
     case tonic::kCompilationErrorType:
       return DartErrorCode::CompilationError;
     case tonic::kApiErrorType:
       return DartErrorCode::ApiError;
     case tonic::kUnknownErrorType:
       return DartErrorCode::UnknownError;
     case tonic::kNoError:
       return DartErrorCode::NoError;
   }
   return DartErrorCode::UnknownError;
 }
References flutter::ApiError, flutter::CompilationError, FML_DCHECK, flutter::TaskRunners::GetPlatformTaskRunner(), flutter::NoError, fml::TaskRunner::RunsTasksOnCurrentThread(), and flutter::UnknownError.
Referenced by flutter::ScriptCompletionTaskObserver::DidProcessTask().
IsSetup()
bool flutter::Shell::IsSetup () const
Used by embedders to check if all shell subcomponents are initialized. It is the embedder's responsibility to make this call before accessing any other shell method. A shell that is not setup must be discarded and another one created with updated settings.
Returns
Returns if the shell has been setup. Once set up, this does not change for the life-cycle of the shell.
Definition at line 447 of file shell.cc.
{
   return is_setup_;
 }
Referenced by flutter::testing::ValidateShell().
NotifyLowMemoryWarning()
void flutter::Shell::NotifyLowMemoryWarning () const
Used by embedders to notify that there is a low memory warning. The shell will attempt to purge caches. Current, only the rasterizer cache is purged.
Definition at line 363 of file shell.cc.
{
   task_runners_.GetGPUTaskRunner()->PostTask(
       [rasterizer = rasterizer_->GetWeakPtr()]() {
         if (rasterizer) {
           rasterizer->NotifyLowMemoryWarning();
         }
       });
   // The IO Manager uses resource cache limits of 0, so it is not necessary
   // to purge them.
 }
References flutter::TaskRunners::GetGPUTaskRunner(), and fml::TaskRunner::PostTask().
RunEngine() [1/2]
void flutter::Shell::RunEngine (RunConfiguration run_configuration)
Starts an isolate for the given RunConfiguration.
Definition at line 374 of file shell.cc.
{
   RunEngine(std::move(run_configuration), nullptr);
 }
Referenced by flutter::testing::ShellTest::RunEngine().
RunEngine() [2/2]
void flutter::Shell::RunEngine (RunConfiguration run_configuration, std::function< void(Engine::RunStatus)> result_callback)
Starts an isolate for the given RunConfiguration. The result_callback will be called with the status of the operation.
Definition at line 378 of file shell.cc.
{
   auto result = [platform_runner = task_runners_.GetPlatformTaskRunner(),
                  result_callback](Engine::RunStatus run_result) {
     if (!result_callback) {
       return;
     }
     platform_runner->PostTask(
         [result_callback, run_result]() { result_callback(run_result); });
   };
   FML_DCHECK(is_setup_);
   FML_DCHECK(task_runners_.GetPlatformTaskRunner()->RunsTasksOnCurrentThread());
   if (!weak_engine_) {
     result(Engine::RunStatus::Failure);
   }
   fml::TaskRunner::RunNowOrPostTask(
       task_runners_.GetUITaskRunner(),
       fml::MakeCopyable(
           [run_configuration = std::move(run_configuration),
            weak_engine = weak_engine_, result]() mutable {
             if (!weak_engine) {
               FML_LOG(ERROR)
                   << "Could not launch engine with configuration - no engine.";
               result(Engine::RunStatus::Failure);
               return;
             }
             auto run_result = weak_engine->Run(std::move(run_configuration));
             if (run_result == flutter::Engine::RunStatus::Failure) {
               FML_LOG(ERROR) << "Could not launch engine with configuration.";
             }
             result(run_result);
           }));
 }
References flutter::Engine::Failure, FML_DCHECK, FML_LOG, flutter::TaskRunners::GetPlatformTaskRunner(), flutter::TaskRunners::GetUITaskRunner(), fml::MakeCopyable(), result, fml::TaskRunner::RunNowOrPostTask(), and fml::TaskRunner::RunsTasksOnCurrentThread().
Screenshot()
Rasterizer::Screenshot flutter::Shell::Screenshot (Rasterizer::ScreenshotType type, bool base64_encode)
Captures a screenshot and optionally Base64 encodes the data of the last layer tree rendered by the rasterizer in this shell.
Parameters
[in] type The type of screenshot to capture.
[in] base64_encode If the screenshot data should be base64 encoded.
Returns
The screenshot result.
Definition at line 1315 of file shell.cc.
{
   TRACE_EVENT0("flutter", "Shell::Screenshot");
   fml::AutoResetWaitableEvent latch;
   Rasterizer::Screenshot screenshot;
   fml::TaskRunner::RunNowOrPostTask(
       task_runners_.GetGPUTaskRunner(), [&latch,                        //
                                          rasterizer = GetRasterizer(),  //
                                          &screenshot,                   //
                                          screenshot_type,               //
                                          base64_encode                  //
   ]() {
         if (rasterizer) {
           screenshot = rasterizer->ScreenshotLastLayerTree(screenshot_type,
                                                            base64_encode);
         }
         latch.Signal();
       });
   latch.Wait();
   return screenshot;
 }
References flutter::TaskRunners::GetGPUTaskRunner(), GetRasterizer(), fml::TaskRunner::RunNowOrPostTask(), fml::AutoResetWaitableEvent::Signal(), TRACE_EVENT0, and fml::AutoResetWaitableEvent::Wait().
WaitForFirstFrame()
fml::Status flutter::Shell::WaitForFirstFrame (fml::TimeDelta timeout)
Pauses the calling thread until the first frame is presented.
Returns
'kOk' when the first frame has been presented before the timeout successfully, 'kFailedPrecondition' if called from the GPU or UI thread, 'kDeadlineExceeded' if there is a timeout.
Definition at line 1338 of file shell.cc.
{
   FML_DCHECK(is_setup_);
   if (task_runners_.GetUITaskRunner()->RunsTasksOnCurrentThread() ||
       task_runners_.GetGPUTaskRunner()->RunsTasksOnCurrentThread()) {
     return fml::Status(fml::StatusCode::kFailedPrecondition,
                        "WaitForFirstFrame called from thread that can't wait "
                        "because it is responsible for generating the frame.");
   }
   std::unique_lock<std::mutex> lock(waiting_for_first_frame_mutex_);
   bool success = waiting_for_first_frame_condition_.wait_for(
       lock, std::chrono::milliseconds(timeout.ToMilliseconds()),
       [& waiting_for_first_frame = waiting_for_first_frame_] {
         return !waiting_for_first_frame.load();
       });
   if (success) {
     return fml::Status();
   } else {
     return fml::Status(fml::StatusCode::kDeadlineExceeded, "timeout");
   }
 }
References FML_DCHECK, flutter::TaskRunners::GetGPUTaskRunner(), flutter::TaskRunners::GetUITaskRunner(), fml::kDeadlineExceeded, fml::kFailedPrecondition, fml::TaskRunner::RunsTasksOnCurrentThread(), and fml::TimeDelta::ToMilliseconds().
Friends And Related Function Documentation
testing::ShellTest
friend class testing::ShellTest friend
Definition at line 510 of file shell.h.
The documentation for this class was generated from the following files:
shell/common/shell.h
shell/common/shell.cc