name: Build

on:
  push:
    branches: [ "main" ]
    tags:
      - v*.*.*
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build with CMake
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-15
          - macos-15-intel
          - ubuntu-24.04
          - ubuntu-24.04-arm
    steps:
    - uses: actions/checkout@v4
    - name: Setup VCPKG
      uses: lukka/run-vcpkg@v11
      env:
        VCPKG_BINARY_SOURCES: default,rw
    # Cache vcpkg binary sources.
    # Adapted from https://github.com/lukka/run-vcpkg/issues/251
    - name: Set up binary cache
      uses: actions/cache@v4
      with:
        path: ${{ env.VCPKG_DEFAULT_BINARY_CACHE }}
        key: ${{ runner.os }}-vcpkg-binary-cache-${{ hashFiles('vcpkg*.json') }}
        restore-keys: |
            ${{ runner.os }}-vcpkg-binary-cache-
    - uses: extractions/setup-just@v3
    - name: Compile and Package
      run: just ci-build-package
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: doxygen2docset_${{ runner.os }}_${{ runner.arch }}
        path: build/to_upload
        if-no-files-found: error
  release:
    permissions:
      contents: write
    name: Release Builds
    runs-on: ubuntu-24.04
    needs: build
    if: github.ref_type == 'tag'
    steps:
      - name: Download artifacts.
        uses: actions/download-artifact@v5
        with:
          pattern: doxygen2docset_*
          path: dist
      - uses: softprops/action-gh-release@v2
        with:
          files: dist/**/*
          generate_release_notes: true
